010_画面設計/Macss/MacssWeb/Areas/Aims/Controllers/D002Controller.cs
using Macss.Database.Entity;
using MacssWeb.Common;
using MacssWeb.Models;
using MacssWeb.Controllers;
using Sic.Common.Attribute;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Optimization;

namespace MacssWeb.Areas.Aims.Controllers
{
    public class D002Controller : BaseController
    {

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details()
        {
            return View();
        }

    }
}

010_画面設計/Macss/MacssWeb/Areas/Dcos/Controllers/D002Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Macss.Database.Entity;
using MacssWeb.Common;
using MacssWeb.Models;
using MacssWeb.Controllers;
using Sic.Common.Attribute;
using System.IO;
using System.Net;
using System.Web.Optimization;

namespace MacssWeb.Areas.Dcos.Controllers
{
    public class D002Controller : Controller
    {
        // GET: Dcos/D002
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            ViewBag.InputFlg = true;
            ViewBag.CreateFlg = true;
            return View();
        }
        public ActionResult Details()
        {
            return View();
        }

        public ActionResult CreateConfirm()
        {
            return View();
        }
        public ActionResult Edit()
        {
            return View();
        }
        public ActionResult EditConfirm()
        {
            return View();
        }
        public ActionResult DeleteConfirm()
        {
            return View();
        }
        public ActionResult Upload()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadConfirm(HttpPostedFileWrapper postedFile)
        {
            if (postedFile == null)
            {
                ViewBag.ErrorMessage = "ファイルがありません。";
                return View(nameof(Upload));
            }

            var ext = Path.GetExtension(postedFile.FileName);

            if (String.Compare(ext, ".csv", true) != 0)
            {
                ViewBag.ErrorMessage = "拡張子が許可されていません。";
                return View(nameof(Upload));
            }

            if (Directory.Exists(Server.MapPath("~/App_Data/Uploaded/")) == false)
            {
                Directory.CreateDirectory(Server.MapPath("~/App_Data/Uploaded/"));
            }

            var uploadPath = Path.Combine(
                Server.MapPath("~/App_Data/Uploaded/"), Path.GetFileName(postedFile.FileName));

            postedFile.SaveAs(uploadPath);

            //var model = MacssDb.m_account.ToList();
            var list = new List<AccountMasterUpload>();

            var i = 0;
            var cntNew = 0;
            var cntUpd = 0;
            var cntDel = 0;

            //foreach (var item in model)
            //{
            //    var uploadData = new AccountMasterUpload(item);

            //    uploadData.Index = ++i;

            //    if (i % 3 == 0)
            //    {
            //        uploadData.ProcType = ProcTypes.Update;
            //        cntUpd++;
            //    }
            //    else if (i % 7 == 0)
            //    {
            //        uploadData.ProcType = ProcTypes.Delete;
            //        cntDel++;
            //    }
            //    else
            //    {
            //        uploadData.ProcType = ProcTypes.New;
            //        cntNew++;
            //    }

            //    list.Add(uploadData);

            //}

            TempData["UploadedList"] = list;

            ViewBag.ConfirmMessage = Resources.Messages.UploadConfirm;
            ViewBag.UploadFileName = postedFile.FileName;
            ViewBag.UploadFileNameWithSize = String.Format("{0} (サイズ：{1:#,0}バイト)"
                , postedFile.FileName, postedFile.ContentLength);
            ViewBag.UploadFileContentsCount = String.Format("{0} 件", i);

            ViewBag.NewCountText = String.Format("新規：{0} 件", cntNew);
            ViewBag.UpdCountText = String.Format("更新：{0} 件", cntUpd);
            ViewBag.DelCountText = String.Format("削除：{0} 件", cntDel);

            //return View(list);
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadResult(string uploadFileName)
        {
            var list = TempData["UploadedList"] as List<AccountMasterUpload>;
            var resultList = new List<AccountMasterUpload>();

            ViewBag.HasError = true;
            //foreach (var item in list)
            //{
            //    if (item.Index % 5 == 0)
            //    {
            //        item.ErrorMessage = "既に登録されています。";
            //        item.HasError = true;
            //    }
            //    else if (item.Index % 14 == 0)
            //    {
            //        item.ErrorMessage = "対象データがありません。";
            //        item.HasError = true;
            //    }
            //    else
            //    {
            //        item.HasError = false;
            //    }

            //    if (item.HasError)
            //    {
            //        ViewBag.HasError = true;
            //        resultList.Add(item);
            //    }
            //}

            ViewBag.UploadFileName = uploadFileName;
            ViewBag.UploadedCount = String.Format("{0} 件", list.Count);
            ViewBag.ErrorCount = String.Format("{0} 件", resultList.Count);

            ViewBag.AlertType = ValueAttribute.GetValue(AlertTypes.Success);
            ViewBag.ResultMessage = Resources.Messages.UploadCompleteSuccess;
            //if (ViewBag.HasError)
            //{
            //    ViewBag.AlertType = ValueAttribute.GetValue(AlertTypes.Warning);
            //    ViewBag.ResultMessage = Resources.Messages.UploadCompleteFailure;
            //}


            return View(resultList);

        }
        public ActionResult AutoAllocationConfirm()
        {
            ViewBag.ConfirmMessage = "自動引当を実行します。よろしいですか？";

            return View();
        }
    }
}

010_画面設計/Macss/MacssWeb/Areas/Pats/Controllers/D002Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MacssWeb.Areas.Pats.Controllers
{
    public class D002Controller : Controller
    {
        // GET: Pats/D002
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 検収一覧
        /// </summary>
        /// <returns></returns>
        public ActionResult D002_01()
        {
            ViewBag.Title = Resources.Pats.Acceptance + "一覧";
            ViewBag.PageMainTitle = Resources.Pats.Acceptance + "一覧";
            ViewBag.ScreenId = "PATS-D002-01";

            return View();
        }

        /// <summary>
        /// 検収詳細確認
        /// </summary>
        /// <returns></returns>
        public ActionResult D002_02()
        {
            ViewBag.Title = Resources.Pats.Acceptance + "詳細確認";
            ViewBag.PageMainTitle = Resources.Pats.Acceptance + "詳細確認";
            ViewBag.ScreenId = "PATS-D002-02";
            ViewBag.OnlyShow = true;

            return View();
        }

        /// <summary>
        /// 検収登録
        /// </summary>
        /// <returns></returns>
        public ActionResult D002_03(string kanbun)
        {
            ViewBag.Title = Resources.Pats.Acceptance + "登録";
            ViewBag.PageMainTitle = Resources.Pats.Acceptance + "登録";
            ViewBag.ScreenId = "PATS-D002-03";
            ViewBag.KanBun = kanbun;

            return View();
        }

        /// <summary>
        /// 検収登録確認
        /// </summary>
        /// <returns></returns>
        public ActionResult D002_04()
        {
            ViewBag.Title = Resources.Pats.Acceptance + "登録確認";
            ViewBag.PageMainTitle = Resources.Pats.Acceptance + "登録確認";
            ViewBag.ScreenId = "PATS-D002-04";
            ViewBag.ConfirmMessage = Resources.Messages.CreateConfirm;
            ViewBag.ButtonText = Resources.ControlText.CreateExec;
            ViewBag.ConfirmDialogText = Resources.Messages.CreateConfirm;

            return View();
        }

        /// <summary>
        /// 検収更新
        /// </summary>
        /// <returns></returns>
        public ActionResult D002_05()
        {
            ViewBag.Title = Resources.Pats.Acceptance + "更新";
            ViewBag.PageMainTitle = Resources.Pats.Acceptance + "更新";
            ViewBag.ScreenId = "PATS-D002-05";

            return View();
        }

        /// <summary>
        /// 検収更新確認
        /// </summary>
        /// <returns></returns>
        public ActionResult D002_06()
        {
            ViewBag.Title = Resources.Pats.Acceptance + "更新確認";
            ViewBag.PageMainTitle = Resources.Pats.Acceptance + "更新確認";
            ViewBag.ScreenId = "PATS-D002-06";
            ViewBag.ConfirmMessage = Resources.Messages.EditConfirm;
            ViewBag.ButtonText = Resources.ControlText.EditExec;
            ViewBag.ConfirmDialogText = Resources.Messages.EditReconfirm;

            return View();
        }

        /// <summary>
        /// 検収削除確認
        /// </summary>
        /// <returns></returns>
        public ActionResult D002_07()
        {
            ViewBag.Title = Resources.Pats.Acceptance + "削除確認";
            ViewBag.PageMainTitle = Resources.Pats.Acceptance + "削除確認";
            ViewBag.ScreenId = "PATS-D002-07";
            ViewBag.ConfirmMessage = Resources.Messages.DeleteConfirm;
            ViewBag.ButtonText = Resources.ControlText.DeleteExec;
            ViewBag.ConfirmDialogText = Resources.Messages.DeleteReconfirm;

            return View();
        }
    }
}

010_画面設計/Macss/MacssWeb/Areas/Tass/Views/D002/CopyConfirm.cshtml
@model Macss.Database.Entity.AccountMaster

@{
    ViewBag.Title = "運送業務 - TASS";
    ViewBag.PageMainTitle = "出荷手配登録確認";
    ViewBag.ScreenId = "";
    ViewBag.ConfirmMessage = MacssWeb.Resources.Messages.CopyConfirm;
    ViewBag.ButtonText = MacssWeb.Resources.ControlText.CopyExec;
    ViewBag.ConfirmDialogText = MacssWeb.Resources.Messages.CopyReconfirm;
}

@using (Html.BeginForm("Copy", "D002", null, FormMethod.Post))
{

    @Html.Partial("_Show", Model)
}

010_画面設計/Macss/MacssWeb/Areas/Tass/Views/D002/Create.cshtml
@using System.Web.Optimization
@model Macss.Database.Entity.AccountMaster

@{
    ViewBag.Title = "運送業務 - TASS";
    ViewBag.PageMainTitle = "出荷手配登録";
    ViewBag.ScreenId = "";
}




@using (Html.BeginForm("CreateConfirm", "D002", null, FormMethod.Post))
{

    @Html.Hidden("preAction", MacssWeb.Common.Actions.Create);

    @Html.Partial("_Form", Model)

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

010_画面設計/Macss/MacssWeb/Areas/Tass/Views/D002/CreateConfirm.cshtml
@model Macss.Database.Entity.AccountMaster

@{
    ViewBag.Title = "運送業務 - TASS";
    ViewBag.PageMainTitle = "出荷手配登録確認";
    ViewBag.ScreenId = "";
    ViewBag.ConfirmMessage = MacssWeb.Resources.Messages.CreateConfirm;
    ViewBag.ButtonText = MacssWeb.Resources.ControlText.CreateExec;
    ViewBag.ConfirmDialogText = MacssWeb.Resources.Messages.CreateReconfirm;
}

@using (Html.BeginForm("Create", "D002", null, FormMethod.Post))
{

    @Html.Partial("_Show", Model)
}

010_画面設計/Macss/MacssWeb/Areas/Tass/Views/D002/DeleteConfirm.cshtml
@model Macss.Database.Entity.AccountMaster

@{
    ViewBag.Title = "運送業務 - TASS";
    ViewBag.PageMainTitle = "出荷手配削除確認";
    ViewBag.ScreenId = "";
    ViewBag.ConfirmMessage = MacssWeb.Resources.Messages.DeleteConfirm;
    ViewBag.ButtonText = MacssWeb.Resources.ControlText.DeleteExec;
    ViewBag.ConfirmDialogText = MacssWeb.Resources.Messages.DeleteReconfirm;
}

@using (Html.BeginForm("Delete", "D002", null, FormMethod.Post))
{

    @Html.Partial("_Show")
}

010_画面設計/Macss/MacssWeb/Areas/Tass/Views/D002/Details.cshtml
@model Macss.Database.Entity.AccountMaster

@{
    ViewBag.Title = "運送業務 - TASS";
    ViewBag.PageMainTitle = "出荷手配詳細確認";
    ViewBag.ScreenId = "";
    ViewBag.OnlyShow = true;
}

@Html.Partial("_Show")

010_画面設計/Macss/MacssWeb/Areas/Tass/Views/D002/Edit.cshtml
@using System.Web.Optimization
@model Macss.Database.Entity.AccountMaster

@{
    ViewBag.Title = "運送業務 - TASS";
    ViewBag.PageMainTitle = "出荷手配更新";
    ViewBag.ScreenId = "";
}

@using (Html.BeginForm("EditConfirm", "D002", null, FormMethod.Post))
{

    @Html.Partial("_Form", Model)

}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

010_画面設計/Macss/MacssWeb/Areas/Tass/Views/D002/EditConfirm.cshtml
@model Macss.Database.Entity.AccountMaster

@{
    ViewBag.Title = "運送業務 - TASS";
    ViewBag.PageMainTitle = "出荷手配更新確認";
    ViewBag.ScreenId = "";
    ViewBag.ConfirmMessage = MacssWeb.Resources.Messages.EditConfirm;
    ViewBag.ButtonText = MacssWeb.Resources.ControlText.EditExec;
    ViewBag.ConfirmDialogText = MacssWeb.Resources.Messages.EditReconfirm;
}

@using (Html.BeginForm("Edit", "D002", null, FormMethod.Post))
{

    @Html.Partial("_Show", Model)
}

010_画面設計/Macss/MacssWeb/Areas/Tass/Views/D002/Upload.cshtml
@{
    ViewBag.Title = "運送業務 - TASS";
    ViewBag.ScreenId = "";
    ViewBag.PageMainTitle = "出荷手配データアップロード";
    ViewBag.Caption = "データのアップロードを行います。";
    //ViewBag.UploadFileAccept = new List<string>() { ".csv, .txt" };
    ViewBag.UploadFileAccept = new List<string>() { ".csv" };
}


    @using (Html.BeginForm("UploadConfirm", "D002", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.Partial("_SimpleUpload")
}

010_画面設計/Macss/MacssWeb/Areas/Tass/Views/D002/UploadConfirm.cshtml
@model IEnumerable<MacssWeb.Models.AccountMasterUpload>

@{
    ViewBag.Title = "運送業務 - TASS";
    ViewBag.ScreenId = "";
    ViewBag.PageMainTitle = "出荷手配データアップロード確認";
}
@section Scripts {
    <script>
        $(function () {

            var dt = new Macss.DataTables.MacssDataTable("#UploadConfirmList");
            dt.setScrollY("600px");
            dt.configure();

        });
    </script>
}

<div class="alert alert-info">
    <span>@ViewBag.ConfirmMessage</span>
</div>

<div class="row justify-content-between macss-form-button-group-row">
    <div class="col-4">
        <a role="button" class="btn btn-secondary" href="@Url.Action("Upload")">@MacssWeb.Resources.ControlText.BackToUpload</a>
    </div>
    <div class="col-4 text-right">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ConfirmDialog">@MacssWeb.Resources.ControlText.UploadExec</button>
    </div>
</div>

<div class="container-fluid mt-4">
    <div class="form-inline">
        <div class="input-group mr-2 mb-1">
            <div class="input-group-prepend">
                <span class="input-group-text">ファイル</span>
            </div>
            <span class="form-control">@ViewBag.UploadFileNameWithSize</span>
        </div>
        <div class="input-group mr-2 mb-1">
            <div class="input-group-prepend">
                <span class="input-group-text">件数</span>
            </div>
            <span class="form-control">6 件@*@ViewBag.UploadFileContentsCount*@</span>
        </div>
    </div>
</div>

<!--
<div class="container-fluid mt-4">
    <div class="macss-label-like-btn-primary">新規：1 件@*@ViewBag.NewCountText*@</div>
    <div class="macss-label-like-btn-sucess">更新：2 件@*@ViewBag.UpdCountText*@</div>
    <div class="macss-label-like-btn-warning">削除：1 件@*@ViewBag.DelCountText*@</div>
</div>
    -->

<!--
<table id="UploadConfirmList" class="table table-striped table-hover macss-data-table">
    <thead class="macss-data-table-header">
        <tr>
            <th>No</th>
            <th>
                出荷日
            </th>
            <th>
                出荷No
            </th>
            <th>
                得意先コード
            </th>
            <th>
                得意先名　　　　　　　　　　　　
            </th>
            <th>
                振替得意先コード
            </th>
            <th>
                出荷統合コード
            </th>
            <th>
                荷札発行済フラグ
            </th>
            <th>
                経費負担No
            </th>
            <th>
                Fe機種コード
            </th>
            <th>
                オリジナル出荷No
            </th>
            <th>
                届先郵便番号
            </th>
            <th>
                届先住所　　　　　　　　　　　　
            </th>
            <th>
                届先社名　　　　　　　　　　
            </th>
            <th>
                品名コード
            </th>
            <th>
                品名　　　　　
            </th>
            <th>
                出荷数
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                1
            </td>
            <td>
                2020/01/04
            </td>
            <td>
                10-03481
            </td>
            <td>
                17601
            </td>
            <td>
                ＦＥ）半導体営業　（松本・ＤＳ）
            </td>
            <td></td>
            <td>
                A104002001
            </td>
            <td>
                発行済
            </td>
            <td></td>
            <td>
                DK
            </td>
            <td></td>
            <td>
                1010052
            </td>
            <td>
                東京都千代田区神田小川町６－１２－１　アンリビル３Ｆ
            </td>
            <td>
                ㈱エイシーエスエヌ
            </td>
            <td>
                001002
            </td>
            <td>
                電気部品
            </td>
            <td>
                50
            </td>
        </tr>
        <tr>
            <td>
                2
            </td>
            <td>
                2020/01/04
            </td>
            <td>
                10-03482
            </td>
            <td>
                17601
            </td>
            <td>
                ＦＥ）半導体営業　（松本・ＤＳ）
            </td>
            <td></td>
            <td>
                A104002001
            </td>
            <td>
                発行済
            </td>
            <td></td>
            <td>
                DK
            </td>
            <td></td>
            <td>
                1010052
            </td>
            <td>
                東京都千代田区神田小川町６－１２－１　アンリビル３Ｆ
            </td>
            <td>
                ㈱エイシーエスエヌ
            </td>
            <td>
                001002
            </td>
            <td>
                電気部品
            </td>
            <td>
                50
            </td>
        </tr>
        <tr>
            <td>
                3
            </td>
            <td>
                2020/01/04
            </td>
            <td>
                10-03483
            </td>
            <td>
                17601
            </td>
            <td>
                ＦＥ）半導体営業　（松本・ＤＳ）
            </td>
            <td></td>
            <td>
                A104002001
            </td>
            <td>
                発行済
            </td>
            <td></td>
            <td>
                DK
            </td>
            <td></td>
            <td>
                1010052
            </td>
            <td>
                東京都千代田区神田小川町６－１２－１　アンリビル３Ｆ
            </td>
            <td>
                ㈱エイシーエスエヌ
            </td>
            <td>
                001002
            </td>
            <td>
                電気部品
            </td>
            <td>
                50
            </td>
        </tr>
    </tbody>
</table>
-->


<div class="modal" id="ConfirmDialog" tabindex="-1" role="dialog" aria-labelledby="ConfirmDialogTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ConfirmDialogTitle">@MacssWeb.Resources.Title.ExecConfirm</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @MacssWeb.Resources.Messages.UploadReconfirm
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("UploadResult", "D002", null, FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="UploadFileName" name="uploadFileName" value="@ViewBag.UploadFileName" />
                    <button type="submit" class="btn btn-primary">@MacssWeb.Resources.ControlText.Yes</button>
                }
                <button type="button" class="btn btn-secondary" data-dismiss="modal">@MacssWeb.Resources.ControlText.No</button>
            </div>
        </div>
    </div>
</div>

010_画面設計/Macss/MacssWeb/Areas/Tass/Views/D002/UploadResult.cshtml
@model IEnumerable<MacssWeb.Models.AccountMasterUpload>

@{
    ViewBag.Title = "運送業務 - TASS";
    ViewBag.ScreenId = "";
    ViewBag.PageMainTitle = "出荷手配データ取込結果";
}
@section Scripts {
    <script>

        $(function () {

            var dt = new Macss.DataTables.MacssDataTable("#UploadConfirmList");
            dt.setScrollY("600px");
            dt.configure();

            $('[data-toggle="popover"]').popover();

        });
    </script>
}

<div class="alert @ViewBag.AlertType">
    <span>@ViewBag.ResultMessage</span>
</div>

<div class="row justify-content-between macss-form-button-group-row">
    <div class="col-4">
        <a role="button" class="btn btn-secondary" href="@Url.Action("Upload")">@MacssWeb.Resources.ControlText.BackToUpload</a>
    </div>
    <div class="col-4 text-right">
        <a role="button" class="btn btn-secondary" href="@Url.Action("Index")">@MacssWeb.Resources.ControlText.BackToList</a>
    </div>
</div>

<div class="container-fluid mt-4">
    <div class="form-inline">
        <div class="input-group mr-2 mb-1">
            <div class="input-group-prepend">
                <span class="input-group-text">ファイル</span>
            </div>
            <span class="form-control">@ViewBag.UploadFileName</span>
        </div>
        <div class="input-group mr-2 mb-1">
            <div class="input-group-prepend">
                <span class="input-group-text">取込件数</span>
            </div>
            <span class="form-control">4 件@*@ViewBag.UploadedCount*@</span>
        </div>
        <div class="input-group mr-2 mb-1">
            <div class="input-group-prepend">
                <span class="input-group-text">エラー件数</span>
            </div>
            <span class="form-control">2 件@*@ViewBag.ErrorCount*@</span>
        </div>
    </div>
</div>

<div class="row mt-2 mb-2">
    <div class="col-12 text-right">
        <div class="dropdown">
            <a class="btn btn-outline-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bars"></i>
            </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#CsvDownloadDialog">CSVダウンロード</a>
            </div>
        </div>
    </div>
</div>

<table id="UploadConfirmList" class="table table-striped table-hover macss-data-table">
    <thead class="macss-data-table-header">
        <!-- thの文字数で列の幅が決まってしまうため、必要に応じて全角スペースを入れて列の幅を調整する必要がある-->
        <tr>
            <th>No</th>
            <!--
    <th>
        処理区分
    </th>
        -->
            <th>
                エラー
            </th>
            <th>出荷日</th>
            <th>オリジナル出荷No</th>
            <th>出荷No</th>
            <th>届先住所　　　　　　　　</th>
            <th>届先名　　　　　　　　　</th>
            <th>品名　　　　　　</th>
            <th>品名カナ　　　　</th>
            <th>出荷数</th>
            <th>得意先コード</th>
            <th>出荷場所コード</th>
            <th>運送方法コード</th>
            <th>経費負担No</th>
            <th>機種コード</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                1
            </td>
            <td>
                <a tabindex="0" class="btn btn-sm btn-danger" role="button" data-toggle="popover"
                   data-trigger="focus" title="エラー詳細"
                   data-content="既に登録されています。">詳細</a>
            </td>
            <td>2020/01/04</td>
            <td></td>
            <td>10-03481</td>
            <td>東京都千代田区神田小川町６－１２－１　アンリビル３Ｆ</td>
            <td>㈱エイシーエスエヌ</td>
            <td>電気部品</td>
            <td></td>
            <td>3</td>
            <td>17601 </td>
            <td>A1</td>
            <td>11</td>
            <td></td>
            <td>DK</td>
        </tr>
    </tbody>
</table>

010_画面設計/Macss/MacssWeb/Areas/Tass/Views/D002/_SimpleUpload.cshtml
@functions {
    public string GetAccept(List<string> accepts, string separator = ", ")
    {
        if(accepts == null || accepts.Count <= 0)
        {
            return String.Empty;
        }

        return String.Join(separator, accepts);
    }

    public string GetUploadFileCaption(List<string> accepts)
    {
        var ext = GetAccept(accepts, "、");

        //return String.Format("拡張子が、{0}で{1}以下のファイルを選択してください。", ext, MacssWeb.Common.Config.UploadMaxFileSizeText);
        return String.Format("EXCEL形式で{0}以下のファイルを選択してください。",  MacssWeb.Common.Config.UploadMaxFileSizeText);
    }
}

@Html.AntiForgeryToken()

<div class="container-fluid">
    <div>
        <p>
            @ViewBag.Caption
        </p>
    </div>
    <div>
        <div>
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="customFile" name="postedFile" accept="@GetAccept(ViewBag.UploadFileAccept)">
                <label class="custom-file-label" for="customFile" data-browse="参 照">ファイル選択...</label>
            </div>
            <small class="form-text text-muted">
                @GetUploadFileCaption(ViewBag.UploadFileAccept)
            </small>
            <div id="UploadErrorMessageArea" style="display:none">
                <span id="UploadErrorMessage" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="mt-4">
        <div>
            <div class="macss-upload-button-group-row pr-0 row">
                <div class="col-8">
                    <a class="btn btn-secondary" href="@Url.Action("Index")" role="button">@MacssWeb.Resources.ControlText.BackToList</a>
                </div>
                <div class="col-4 text-right">
                    <button type="button" id="UploadExec" class="btn btn-primary">@MacssWeb.Resources.ControlText.UploadConfirm</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {

        var fu = new Macss.FileUpload.MacssFileUpload();
        fu.configure();

        $('#UploadExec').on('click', function () {

            var form = $(this).parents('form');
            $("#UploadErrorMessageArea").hide();
            var accepts = [];

            @foreach (var item in ViewBag.UploadFileAccept)
            {
                @:accepts.push("@item");
            }

            var ret = false;

            ret = fu.acceptExt(accepts);

            if (ret == false) {
                $("#UploadErrorMessage").text("@MacssWeb.Resources.Validation.NotAllowedFileExtension");
                $("#UploadErrorMessageArea").show();
                return false;
            }

            ret = fu.withinRangeOfFileSize(@MacssWeb.Common.Config.UploadMaxFileSize);

            if (ret == false) {
                $("#UploadErrorMessage").text("@MacssWeb.Resources.Validation.OverFileSize");
                $("#UploadErrorMessageArea").show();
                return false;
            }

            form.submit();
        });
    })
</script>