010_画面設計/Macss/MacssWeb/Areas/Dcos/Controllers/StockAllocationController.cs
using Macss.Database.Entity;
using MacssWeb.Areas.Dcos.Helper;
using MacssWeb.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MacssWeb.Areas.Dcos.Controllers
{
    [Authorize]
    public class StockAllocationController : StockBaseController
    {
        // GET: Dcos/StockAllocation
        public ActionResult Index()
        {
            ViewBag.StockScreen = StockScreens.StockAllocationIndex;

            var list = CreateSampleData();

            ViewBag.SumAlloc = list.Sum(x => x.AllocationQuantity);
            ViewBag.SumImpossibleAlloc = list.Sum((x) =>
            {
                var total = 0;
                if (x.FixStockRemaining < 0)
                {
                    total += System.Math.Abs(x.FixStockRemaining);
                }
                return total;

            });

            TempData["SampleList"] = list;

            return View(list);
        }

        public ActionResult AutoAllocation()
        {
            return View();
        }

        public ActionResult AutoAllocationConfirm()
        {
            ViewBag.StockScreen = StockScreens.StockAutoAllocation;

            ViewBag.ConfirmMessage = "自動引当を実行します。よろしいですか？";

            var list = CreateSampleData();

            ViewBag.AllocCount = String.Format("引当対象件数：{0} 件", list.Sum(x => x.OutOrderQuantity));
            ViewBag.ImpossibleAllocCount = String.Format("引当不能件数：{0} 件", list.Sum((x) =>
            {
                var total = 0;
                if (x.FixStockRemaining < 0)
                {
                    total += System.Math.Abs(x.FixStockRemaining);
                }
                return total;

            }));

            TempData["SampleList"] = list;

            return View(list);
        }
        public ActionResult AutoAllocationResult()
        {
            ViewBag.StockScreen = StockScreens.StockAutoAllocationResult;

            var list = TempData["SampleList"] as List<DummyStock>;

            ViewBag.AllocCount = String.Format("{0} 件", list.Sum(x => x.AllocationQuantity));
            ViewBag.ImpossibleAllocCount = String.Format("{0} 件", list.Sum((x) =>
            {
                var total = 0;
                if (x.FixStockRemaining < 0)
                {
                    total += System.Math.Abs(x.FixStockRemaining);
                }
                return total;

            }));

            TempData["SampleList"] = list;

            ViewBag.ResultMessage = "在庫引当計画データを作成しました。";

            return View(list);
        }

        //public ActionResult AllocationExec()
        //{
        //    ViewBag.StockScreen = StockScreens.StockAllocationExec;

        //    ViewBag.ConfirmMessage = "以下のデータを計画実施にします。よろしいですか？";

        //    var list = CreateSampleData();

        //    ViewBag.AllocCount = String.Format("引当対象件数：{0} 件", list.Sum(x => x.OutOrderQuantity));
        //    ViewBag.ImpossibleAllocCount = String.Format("引当不能件数：{0} 件", list.Sum((x) =>
        //    {
        //        var total = 0;
        //        if (x.FixStockRemaining < 0)
        //        {
        //            total += System.Math.Abs(x.FixStockRemaining);
        //        }
        //        return total;

        //    }));

        //    TempData["SampleList"] = list;
        //public ActionResult AllocationExecConfirm()
        //{
        //    ViewBag.StockScreen = StockScreens.StockAllocationExec;

        //    ViewBag.ConfirmMessage = "在庫自動引当を実行します。よろしいですか？";

        //    var list = CreateSampleData();

        //    ViewBag.AllocCount = String.Format("引当対象件数：{0} 件", 10);
        //    ViewBag.ImpossibleAllocCount = String.Format("引当不能件数：{0} 件", 1);
        //    //ViewBag.AllocCount = String.Format("引当対象件数：{0} 件", list.Sum(x => x.OutOrderQuantity));
        //    //ViewBag.ImpossibleAllocCount = String.Format("引当不能件数：{0} 件", list.Sum((x) =>
        //    //{
        //    //    var total = 0;
        //    //    if (x.FixStockRemaining < 0)
        //    //    {
        //    //        total += System.Math.Abs(x.FixStockRemaining);
        //    //    }
        //    //    return total;

        //    //}));

        //    //TempData["SampleList"] = list;

        //    //return View(list);

        //    return View();
        ////}
        //    return View(list);
        //}

        public ActionResult AllocationExecResult()
        {
            ViewBag.StockScreen = StockScreens.StockAllocationExec;

            var list = TempData["SampleList"] as List<DummyStock>;

            ViewBag.AllocCount = String.Format("{0} 件", list.Sum(x => x.AllocationQuantity));
            ViewBag.ImpossibleAllocCount = String.Format("{0} 件", list.Sum((x) =>
            {
                var total = 0;
                if (x.FixStockRemaining < 0)
                {
                    total += System.Math.Abs(x.FixStockRemaining);
                }
                return total;

            }));

            TempData["SampleList"] = list;

            ViewBag.ResultMessage = "引当計画実施済になりました。";

            return View(list);
        }
        public ActionResult PickingListOutput()
        {
            ViewBag.StockScreen = StockScreens.StockAllocationPickingList;

            ViewBag.ConfirmMessage = "以下のデータでピッキングリストの出力対象データについてピッキングリストを出力します。";

            var list = CreateSampleData();

            ViewBag.PickingTargetCount = String.Format("ピッキングリスト対象データ件数：{0} 件", list.Sum((x) =>
            {
                var total = 0;
                if (x.PickingListOutput != DummyStock.PickingListOutputStatus.Nothing)
                {
                    total += 1;
                }
                return total;

            }));
            ViewBag.AllocCount = String.Format("引当件数（計画引当件数）：{0} 件", list.Sum(x => x.OutOrderQuantity));
            ViewBag.ImpossibleAllocCount = String.Format("引当不能件数：{0} 件", list.Sum((x) =>
            {
                var total = 0;
                if (x.FixStockRemaining < 0)
                {
                    total += System.Math.Abs(x.FixStockRemaining);
                }
                return total;

            }));

            TempData["SampleList"] = list;

            return View(list);
        }
        public ActionResult AllocationPlanCancelConfirm()
        {
            ViewBag.StockScreen = StockScreens.StockAllocationPlanCancel;

            ViewBag.ConfirmMessage = "以下のデータの引当計画実施済を解除します。よろしいですか？";

            var list = CreateSampleData();

            ViewBag.AllocCount = String.Format("引当件数（計画実施済引当件数）：{0} 件", list.Sum(x => x.AllocationExecQuantity));
            //ViewBag.ImpossibleAllocCount = String.Format("引当不能数：{0} 件", list.Sum((x) =>
            //{
            //    var total = 0;
            //    if (x.FixStockRemaining < 0)
            //    {
            //        total += System.Math.Abs(x.FixStockRemaining);
            //    }
            //    return total;

            //}));

            TempData["SampleList"] = list;

            return View(list);
        }
        public ActionResult AllocationPlanCancelResult()
        {
            ViewBag.StockScreen = StockScreens.StockAllocationPlanCancel;

            var list = TempData["SampleList"] as List<DummyStock>;
            if (list == null || list.Count <= 0)
            {
                return RedirectToAction(nameof(Index));
            }

            ViewBag.AllocCount = String.Format("{0} 件", list.Sum(x => x.AllocationQuantity));
            //ViewBag.ImpossibleAllocCount = String.Format("{0} 件", list.Sum((x) =>
            //{
            //    var total = 0;
            //    if (x.FixStockRemaining < 0)
            //    {
            //        total += System.Math.Abs(x.FixStockRemaining);
            //    }
            //    return total;

            //}));

            TempData["SampleList"] = list;

            ViewBag.ResultMessage = "引当計画実施済を解除しました。";

            return View(list);
        }
        public ActionResult AllocationPlanListFixConfirm()
        {
            ViewBag.StockScreen = StockScreens.StockAllocationPlanFix;

            ViewBag.ConfirmMessage = "以下のデータの引当計画を確定します。よろしいですか？";

            var list = CreateSampleData();

            ViewBag.AllocCount = String.Format("引当件数（計画実施済引当件数）：{0} 件", list.Sum(x => x.AllocationExecQuantity));
            //ViewBag.ImpossibleAllocCount = String.Format("引当不能数：{0} 件", list.Sum((x) =>
            //{
            //    var total = 0;
            //    if (x.FixStockRemaining < 0)
            //    {
            //        total += System.Math.Abs(x.FixStockRemaining);
            //    }
            //    return total;

            //}));

            TempData["SampleList"] = list;

            return View(list);
        }
        public ActionResult AllocationPlanListFixResult()
        {
            ViewBag.StockScreen = StockScreens.StockAllocationPlanFix;

            var list = TempData["SampleList"] as List<DummyStock>;
            if (list == null || list.Count <= 0)
            {
                return RedirectToAction(nameof(Index));
            }

            ViewBag.AllocCount = String.Format("{0} 件", list.Sum(x => x.AllocationQuantity));
            //ViewBag.ImpossibleAllocCount = String.Format("{0} 件", list.Sum((x) =>
            //{
            //    var total = 0;
            //    if (x.FixStockRemaining < 0)
            //    {
            //        total += System.Math.Abs(x.FixStockRemaining);
            //    }
            //    return total;

            //}));

            TempData["SampleList"] = list;

            ViewBag.ResultMessage = "引当計画を確定しました。";

            return View(list);
        }
        public ActionResult AllocationPlanListFixCancelConfirm()
        {
            ViewBag.StockScreen = StockScreens.StockAllocationPlanFixCancel;

            ViewBag.ConfirmMessage = "以下のデータの引当計画確定済を解除します。よろしいですか？";

            var list = CreateSampleData();

010_画面設計/Macss/MacssWeb/Areas/Dcos/Views/StockAllocation/AllocationExecCancelConfirm.cshtml
@{
    ViewBag.PageMainTitle = "在庫引当実施解除確認";
}
@section Scripts {
    <script>
        $(function () {

            var dt = new Macss.DataTables.MacssDataTable("#SampleList", [{
                "className": "macss-table-proc-column", "width": 80, "orderable": false, "targets": 0
            },], 1);
            dt.configure();

            var cond = new Macss.Collapse.ConditionsPanel("#ConditionAccordion", "#CollapseShow", "#CollapseHidden");
            cond.setCollapseEvent();

            var sampleDatePicker11 = new Macss.DatetimePicker.MacssDtPicker("#SampleDTPicker11", "#SampleCalendar11");
            sampleDatePicker11.configure();
            var sampleDatePicker12 = new Macss.DatetimePicker.MacssDtPicker("#SampleDTPicker12", "#SampleCalendar12");
            sampleDatePicker12.configure();
            var sampleDatePicker21 = new Macss.DatetimePicker.MacssDtPicker("#SampleDTPicker21", "#SampleCalendar21");
            sampleDatePicker21.configure();
            var sampleDatePicker22 = new Macss.DatetimePicker.MacssDtPicker("#SampleDTPicker22", "#SampleCalendar22");
            sampleDatePicker22.configure();

        });

    </script>
}

@section CssExtended{
    <style type="text/css">
    </style>
}

@Html.Partial("../../Views/Shared/Dialog/_DepartmentCodeSearch")


@using (Html.BeginForm("Search", "Stock", null, FormMethod.Post))
{
    <div class="alert alert-info">
        <span>以下を引当実施解除します。よろしいですか？</span>
    </div>
    <div class="row justify-content-between macss-form-button-group-row">
        <div class="col-4">
            <a class="btn btn-secondary" href="@Url.Action("Index")" role="button">戻る</a>
        </div>
    </div>

    <div class="accordion" id="ConditionAccordion">
        <div class="card">
            <div class="card-header macss-search-config-collapse-header" id="headingOne">
                <div class="mb-0">
                    <button class="btn macss-btn-condition-collapse" type="button" data-toggle="collapse" data-target="#ConditionMain" aria-expanded="true" aria-controls="ConditionMain">
                        <div class="d-inline-block" style="color:#333"></div>
                        <i id="CollapseHidden" class="fas fa-chevron-circle-up" aria-hidden="true" style="display:none;"></i>
                        <i id="CollapseShow" class="fas fa-chevron-circle-down" aria-hidden="true" style="display:none;"></i>
                    </button>
                </div>
            </div>
            <div id="ConditionMain" class="container-fluid mt-3 mb-3 pr-1 collapse show" aria-labelledby="headingOne" data-parent="#ConditionAccordion">
                <table class="table macss-form-table2">
                    <colgroup>
                        <col class="macss-form-table-title2">
                        <col class="macss-form-table-contents2">
                    </colgroup>
                    <tbody>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">得意先</label>
                            </th>
                            <td>
                                <div>

                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}

<table id="SampleList" class="table table-striped table-hover macss-data-table">
    <thead class="macss-data-table-header">
        <!-- thの文字数で列の幅が決まってしまうため、必要に応じて全角スペースを入れて列の幅を調整する必要がある-->
        <tr>
            <th>出庫指示No</th>
            <th>出庫指示枝番</th>
            <th>引当枝番</th>
            <th>伝票区分</th>
            <th>出庫日</th>
            <th>オリジナル出庫指示No</th>
            <th>倉庫コード</th>
            <th>倉庫名</th>
            <th>品名コード</th>
            <th>品名</th>
            <th>ロットNo</th>
            <th>棚番</th>
            <th>引当数量</th>
            <th>出庫指示数量</th>
            <th>引当可能数量</th>
            <th>保存期限</th>
            <th>伝票No</th>
            <th>備考</th>
            <th>発生元区分</th>
            <th>出庫指示ロットNo</th>
            <th>出庫指示棚番</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>

<div class="mt-4"></div>
<div class="row justify-content-between macss-form-button-group-row">
    <div class="col-4">
        <a class="btn btn-secondary" href="@Url.Action("Index")" role="button">戻る</a>
    </div>
    <div class="col-4 text-right">
        <a role="button" class="btn btn-primary" data-toggle="modal" data-target="#ConfirmDialog">引当実施解除</a>
    </div>
</div>

<div class="modal" id="ConfirmDialog" tabindex="-1" role="dialog" aria-labelledby="ConfirmDialogTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ConfirmDialogTitle">@MacssWeb.Resources.Title.ExecConfirm</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                引当実施解除処理を実行します。よろしいですか？
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("Index", "StockAllocation", null, FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="UploadFileName" name="uploadFileName" value="@ViewBag.UploadFileName" />
                    <button type="submit" class="btn btn-primary">@MacssWeb.Resources.ControlText.Yes</button>
                }
                <button type="button" class="btn btn-secondary" data-dismiss="modal">@MacssWeb.Resources.ControlText.No</button>
            </div>
        </div>
    </div>
</div>

010_画面設計/Macss/MacssWeb/Areas/Dcos/Views/StockAllocation/AllocationExecConfirm.cshtml
@{
    ViewBag.PageMainTitle = "在庫引当実施確認";
}
@section Scripts {
    <script>
        $(function () {

            var dt = new Macss.DataTables.MacssDataTable("#SampleList", [{
                "className": "macss-table-proc-column", "width": 80, "orderable": false, "targets": 0
            },], 1);
            dt.configure();

            var cond = new Macss.Collapse.ConditionsPanel("#ConditionAccordion", "#CollapseShow", "#CollapseHidden");
            cond.setCollapseEvent();

            var sampleDatePicker11 = new Macss.DatetimePicker.MacssDtPicker("#SampleDTPicker11", "#SampleCalendar11");
            sampleDatePicker11.configure();
            var sampleDatePicker12 = new Macss.DatetimePicker.MacssDtPicker("#SampleDTPicker12", "#SampleCalendar12");
            sampleDatePicker12.configure();
            var sampleDatePicker21 = new Macss.DatetimePicker.MacssDtPicker("#SampleDTPicker21", "#SampleCalendar21");
            sampleDatePicker21.configure();
            var sampleDatePicker22 = new Macss.DatetimePicker.MacssDtPicker("#SampleDTPicker22", "#SampleCalendar22");
            sampleDatePicker22.configure();

        });

    </script>
}

@section CssExtended{
    <style type="text/css">
    </style>
}

@Html.Partial("../../Views/Shared/Dialog/_DepartmentCodeSearch")


@using (Html.BeginForm("Search", "Stock", null, FormMethod.Post))
{
    <div class="alert alert-info">
        <span>以下を引当実施します。よろしいですか？</span>
    </div>
    <div class="row justify-content-between macss-form-button-group-row">
        <div class="col-4">
            <a class="btn btn-secondary" href="@Url.Action("Index")" role="button">戻る</a>
        </div>
    </div>

    <div class="accordion" id="ConditionAccordion">
        <div class="card">
            <div class="card-header macss-search-config-collapse-header" id="headingOne">
                <div class="mb-0">
                    <button class="btn macss-btn-condition-collapse" type="button" data-toggle="collapse" data-target="#ConditionMain" aria-expanded="true" aria-controls="ConditionMain">
                        <div class="d-inline-block" style="color:#333"></div>
                        <i id="CollapseHidden" class="fas fa-chevron-circle-up" aria-hidden="true" style="display:none;"></i>
                        <i id="CollapseShow" class="fas fa-chevron-circle-down" aria-hidden="true" style="display:none;"></i>
                    </button>
                </div>
            </div>
            <div id="ConditionMain" class="container-fluid mt-3 mb-3 pr-1 collapse show" aria-labelledby="headingOne" data-parent="#ConditionAccordion">
                <table class="table macss-form-table2">
                    <colgroup>
                        <col class="macss-form-table-title2">
                        <col class="macss-form-table-contents2">
                    </colgroup>
                    <tbody>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">得意先</label>
                            </th>
                            <td>
                                <div>

                                </div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">ピッキングリスト</label>
                            </th>
                            <td>
                                <div>
                                    <div class="row">
                                        <div class="col-4">
                                            <select class="custom-select form-control" id="Condition3" aria-describedby="Condition3">
                                                <option value="43">出力する</option>
                                                <option value="03">出力しない</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}

<table id="SampleList" class="table table-striped table-hover macss-data-table">
    <thead class="macss-data-table-header">
        <!-- thの文字数で列の幅が決まってしまうため、必要に応じて全角スペースを入れて列の幅を調整する必要がある-->
        <tr>
            <th>出庫指示No</th>
            <th>出庫指示枝番</th>
            <th>引当枝番</th>
            <th>伝票区分</th>
            <th>出庫日</th>
            <th>オリジナル出庫指示No</th>
            <th>倉庫コード</th>
            <th>倉庫名</th>
            <th>品名コード</th>
            <th>品名</th>
            <th>ロットNo</th>
            <th>棚番</th>
            <th>引当数量</th>
            <th>出庫指示数量</th>
            <th>引当可能数量</th>
            <th>保存期限</th>
            <th>伝票No</th>
            <th>備考</th>
            <th>発生元区分</th>
            <th>出庫指示ロットNo</th>
            <th>出庫指示棚番</th>


        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>

<div class="mt-4"></div>
<div class="row justify-content-between macss-form-button-group-row">
    <div class="col-4">
        <a class="btn btn-secondary" href="@Url.Action("Index")" role="button">戻る</a>
    </div>
    <div class="col-4 text-right">
        <a role="button" class="btn btn-primary" data-toggle="modal" data-target="#ConfirmDialog">引当実施</a>
    </div>
</div>

<div class="modal" id="ConfirmDialog" tabindex="-1" role="dialog" aria-labelledby="ConfirmDialogTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ConfirmDialogTitle">@MacssWeb.Resources.Title.ExecConfirm</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                引当実施処理を実行します。よろしいですか？
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("Index", "StockAllocation", null, FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="UploadFileName" name="uploadFileName" value="@ViewBag.UploadFileName" />
                    <button type="submit" class="btn btn-primary">@MacssWeb.Resources.ControlText.Yes</button>
                }
                <button type="button" class="btn btn-secondary" data-dismiss="modal">@MacssWeb.Resources.ControlText.No</button>
            </div>
        </div>
    </div>
</div>

010_画面設計/Macss/MacssWeb/Areas/Dcos/Views/StockAllocation/AllocationExecResult.cshtml
@{
    ViewBag.Title = MacssWeb.Resources.Dcos.StockAllocationExecMainTitle;
    ViewBag.PageMainTitle = String.Format("{0}{1}", MacssWeb.Resources.Dcos.StockAllocationExecMainTitle, "結果");
    ViewBag.ScreenId = "DCOS-D003-10";
}

<div class="alert alert-primary">
    <span>@ViewBag.ResultMessage</span>
</div>

<div class="row justify-content-between macss-form-button-group-row">
    <div class="col-12 text-right">
        <a role="button" class="btn btn-secondary" href="@Url.Action("Index")">@MacssWeb.Resources.ControlText.BackToList</a>
    </div>
</div>
<div class="container-fluid mt-4">
    <div class="form-inline">
        <div class="col-4">
            <div class="input-group mr-2 mb-1">
                <div class="input-group-prepend">
                    <span class="input-group-text">実施内容</span>
                </div>
                <span class="form-control">計画実施</span>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid mt-2">
    <div class="form-inline">
        <div class="col-4">
            <div class="input-group mr-2 mb-1">
                <div class="input-group-prepend">
                    <span class="input-group-text">得意先</span>
                </div>
                <span class="form-control">@String.Format("{0} {1}", "71281", "サンプル商事(株)")</span>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid mt-2">
    <div class="form-inline">
        <div class="col-4">
            <div class="input-group mr-2 mb-1">
                <div class="input-group-prepend">
                    <span class="input-group-text">オリジナル出庫指示No</span>
                </div>
                <span class="form-control">123456789012345</span>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid mt-2">
    <div class="form-inline">
        <div class="col-4">
            <div class="input-group mr-2 mb-1">
                <div class="input-group-prepend">
                    <span class="input-group-text">ピッキングリスト</span>
                </div>
                <span class="form-control">出力する</span>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid mt-4">
    <div class="form-inline">
        <div class="input-group mr-2 mb-1">
            <div class="input-group-prepend">
                <span class="input-group-text">引当対象件数</span>
            </div>
            <span class="form-control">@ViewBag.AllocCount</span>
        </div>
        <div class="input-group mr-2 mb-1">
            <div class="input-group-prepend">
                <span class="input-group-text">引当不能件数</span>
            </div>
            <span class="form-control">@ViewBag.ImpossibleAllocCount</span>
        </div>
    </div>
</div>

<div class="row mt-1 mb-1">
    <div class="col-12 text-right">
        <div class="dropdown">
            <a class="btn btn-outline-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bars"></i>
            </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="#">CSVダウンロード</a>
            </div>
        </div>
    </div>
</div>
@Html.Partial("_List")

010_画面設計/Macss/MacssWeb/Areas/Dcos/Views/StockAllocation/AllocationPlanCancelConfirm.cshtml
@{
    ViewBag.Title = MacssWeb.Resources.Dcos.StockAllocationPlanCancelMainTitle;
    ViewBag.PageMainTitle = String.Format("{0}{1}", MacssWeb.Resources.Dcos.StockAllocationPlanCancelMainTitle, "確認");
    ViewBag.ScreenId = "DCOS-D003-12";
}
@section Scripts {
    <script>
        $(function () {

            var dt = new Macss.DataTables.MacssDataTable("#UploadConfirmList");
            dt.setScrollY("600px");
            dt.configure();

        });
    </script>
}

<div class="alert alert-info">
    <span>@ViewBag.ConfirmMessage</span>
</div>

<div class="row justify-content-between macss-form-button-group-row">
    <div class="col-4">
        <a role="button" class="btn btn-secondary" href="@Url.Action("Index")">@MacssWeb.Resources.ControlText.BackToList</a>
    </div>
    <div class="col-4 text-right">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ConfirmDialog">引当計画実施済解除</button>
    </div>
</div>

<div class="container-fluid mt-4">
    <div class="form-inline">
        <div class="input-group mr-2 mb-1">
            <div class="input-group-prepend">
                <span class="input-group-text">得意先</span>
            </div>
            <span class="form-control">@String.Format("{0} {1}", "71281", "サンプル商事(株)")</span>
        </div>
    </div>
</div>

<div class="container-fluid mt-2">
    <div class="form-inline">
        <div class="input-group mr-2 mb-1">
            <div class="input-group-prepend">
                <span class="input-group-text">オリジナル出庫指示No</span>
            </div>
            <span class="form-control">123456789012345</span>
        </div>
    </div>
</div>


<div class="container-fluid mt-4">
    <div class="macss-label-like-btn-primary">@ViewBag.AllocCount</div>
    @*<div class="macss-label-like-btn-warning">@ViewBag.ImpossibleAllocCount</div>*@
</div>

@Html.Partial("_List")

<div class="modal" id="ConfirmDialog" tabindex="-1" role="dialog" aria-labelledby="ConfirmDialogTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ConfirmDialogTitle">@MacssWeb.Resources.Title.ExecConfirm</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                引当計画実施済を解除します。よろしいですか？
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">@MacssWeb.Resources.ControlText.Cancel</button>
                @using (Html.BeginForm("AllocationPlanCancelResult", "StockAllocation", null, FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="UploadFileName" name="uploadFileName" value="@ViewBag.UploadFileName" />
                    <button type="submit" class="btn btn-primary">解除</button>
                }
            </div>
        </div>
    </div>
</div>