010_画面設計/Macss/MacssWeb/Areas/Base/Controllers/D212Controller.cs
using Macss.Database.Entity;
using MacssWeb.Common;
using MacssWeb.Models;
using MacssWeb.Controllers;
using Sic.Common.Attribute;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MacssWeb.Areas.Base.Controllers
{
    public class D212Controller : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Details()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult CreateConfirm()
        {
            return View();
        }

        public ActionResult Edit()
        {
            return View();
        }

        public ActionResult EditConfirm()
        {
            return View();
        }
    }
}

010_画面設計/Macss/MacssWeb/Areas/Base/Views/D212/CreateConfirm.cshtml
@{
    ViewBag.Title = "仕入先別運賃明細登録確認";
    ViewBag.PageMainTitle = "仕入先別運賃明細登録確認";
    ViewBag.ConfirmMessage = MacssWeb.Resources.Messages.DeleteConfirm;
    ViewBag.ButtonText = MacssWeb.Resources.ControlText.DeleteExec;
    ViewBag.ConfirmDialogText = MacssWeb.Resources.Messages.DeleteReconfirm;
}
@section Scripts {
    <script>$(function () {

            var dt = new Macss.DataTables.MacssDataTable("#SampleList");
            dt.configure();

            //MacssDataTable（dataTables.fixedColumns.js）に表示する列が15件以上あると計算間違いで最左端列にスクロールバーが表示されるため、非表示にする
            $('.DTFC_LeftBodyLiner').css('overflow-y', 'hidden');

        });</script>
}
@using (Html.BeginForm("Delete", "Shipping", null, FormMethod.Post))
{
    <div class="alert alert-info">
        <span>以下を登録します。よろしいですか？</span>
    </div>
    <div class="row justify-content-between macss-form-button-group-row">
        <div class="col-4">
            <a class="btn btn-secondary" href="@Url.Action("Create")" role="button">@MacssWeb.Resources.ControlText.Back</a>
        </div>
    </div>
    <div class="accordion" id="ConditionAccordion">
        <div class="card">
            <div class="card-header macss-search-config-collapse-header" id="headingOne">
                <div class="mb-0">
                    <button class="btn macss-btn-condition-collapse" type="button" data-toggle="collapse" data-target="#ConditionMain" aria-expanded="true" aria-controls="ConditionMain">
                        <div class="d-inline-block" style="color:#333"></div>
                        <i id="CollapseHidden" class="fas fa-chevron-circle-up" aria-hidden="true" style="color: rgb(120, 188, 255);"></i>
                        <i id="CollapseShow" class="fas fa-chevron-circle-down" aria-hidden="true" style="color: rgb(120, 188, 255); display: none;"></i>
                    </button>
                </div>
            </div>
            <div id="ConditionMain" class="container-fluid mt-3 mb-3 pr-1 collapse show" aria-labelledby="headingOne" data-parent="#ConditionAccordion">
                <table class="table macss-form-table2">
                    <colgroup>
                        <col class="macss-form-table-title2">
                        <col class="macss-form-table-contents2">
                    </colgroup>
                    <tbody>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">仕入先</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>

                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">運送区分コード1</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>

                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">運送区分コード2</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">運賃明細コード</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">連携元区分</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">仕入先別運賃明細区分</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">基準運賃区分</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">明細適用区分</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">消費税区分</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">明細項番</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">帳票印字順番</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">FB運賃明細コード</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>

                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">使用不可開始日</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">使用不可理由</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}
<div class="mt-4"></div>
<div class="row justify-content-between macss-form-button-group-row">
    <div class="col-4">
        <a class="btn btn-secondary" href="@Url.Action("Create")" role="button">@MacssWeb.Resources.ControlText.Back</a>
    </div>
    <div class="col-4 text-right">
        <a role="button" class="btn btn-primary" data-toggle="modal" data-target="#ConfirmDialog">登録</a>
    </div>
</div>
<div class="modal" id="ConfirmDialog" tabindex="-1" role="dialog" aria-labelledby="ConfirmDialogTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ConfirmDialogTitle">@MacssWeb.Resources.Title.ExecConfirm</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                登録処理を実行します。よろしいですか？
            </div>
            <div class="modal-footer">
                <a class="btn btn-primary macss-btn" href="@Url.Action("Create")" role="button">@MacssWeb.Resources.ControlText.Yes</a>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">@MacssWeb.Resources.ControlText.No</button>
            </div>
        </div>
    </div>
</div>

010_画面設計/Macss/MacssWeb/Areas/Base/Views/D212/Details.cshtml
@model Macss.Database.Entity.AccountMaster
@{
    ViewBag.Title = "仕入先別運賃明細詳細確認";
    ViewBag.PageMainTitle = "仕入先別運賃明細詳細確認";
    ViewBag.ConfirmMessage = MacssWeb.Resources.Messages.DeleteConfirm;
    ViewBag.ButtonText = MacssWeb.Resources.ControlText.DeleteExec;
    ViewBag.ConfirmDialogText = MacssWeb.Resources.Messages.DeleteReconfirm;
}
@section Scripts {
    <script>$(function () {

            var dt = new Macss.DataTables.MacssDataTable("#SampleList");
            dt.configure();

            //MacssDataTable（dataTables.fixedColumns.js）に表示する列が15件以上あると計算間違いで最左端列にスクロールバーが表示されるため、非表示にする
            $('.DTFC_LeftBodyLiner').css('overflow-y', 'hidden');

        });</script>
}
@using (Html.BeginForm("Details", "D212", null, FormMethod.Post))
{
    <div class="row justify-content-between macss-form-button-group-row">
        <div class="col-4">
            <a role="button" class="btn btn-secondary" href="@Url.Action("Index")">@MacssWeb.Resources.ControlText.Back</a>
        </div>
    </div>
    <div class="accordion" id="ConditionAccordion">
        <div class="card">
            <div class="card-header macss-search-config-collapse-header" id="headingOne">
                <div class="mb-0">
                    <button class="btn macss-btn-condition-collapse" type="button" data-toggle="collapse" data-target="#ConditionMain" aria-expanded="true" aria-controls="ConditionMain">
                        <div class="d-inline-block" style="color:#333"></div>
                        <i id="CollapseHidden" class="fas fa-chevron-circle-up" aria-hidden="true" style="color: rgb(120, 188, 255);"></i>
                        <i id="CollapseShow" class="fas fa-chevron-circle-down" aria-hidden="true" style="color: rgb(120, 188, 255); display: none;"></i>
                    </button>
                </div>
            </div>
            <div id="ConditionMain" class="container-fluid mt-3 mb-3 pr-1 collapse show" aria-labelledby="headingOne" data-parent="#ConditionAccordion">
                <table class="table macss-form-table2">
                    <colgroup>
                        <col class="macss-form-table-title2">
                        <col class="macss-form-table-contents2">
                    </colgroup>
                    <tbody>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">仕入先</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>

                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">運送区分コード1</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>

                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">運送区分コード2</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">運賃明細コード</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">連携元区分</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">仕入先別運賃明細区分</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">基準運賃区分</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">明細適用区分</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">消費税区分</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">明細項番</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">帳票印字順番</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">FB運賃明細コード</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>

                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">使用不可開始日</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">使用不可理由</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}

<div class="mt-4">
</div>
<div class="row justify-content-between macss-form-button-group-row">
    <div class="col-4">
        <a role="button" class="btn btn-secondary" href="@Url.Action("Index")">@MacssWeb.Resources.ControlText.Back</a>
    </div>
    <div class="col-4 text-right">
        <a role="button" class="btn btn-primary" href="@Url.Action("Edit")">@MacssWeb.Resources.ControlText.Edit</a>
    </div>
</div>

010_画面設計/Macss/MacssWeb/Areas/Base/Views/D212/EditConfirm.cshtml
@{
    ViewBag.Title = "仕入先別運賃明細更新確認";
    ViewBag.PageMainTitle = "仕入先別運賃明細更新確認";
    ViewBag.ConfirmMessage = MacssWeb.Resources.Messages.DeleteConfirm;
    ViewBag.ButtonText = MacssWeb.Resources.ControlText.DeleteExec;
    ViewBag.ConfirmDialogText = MacssWeb.Resources.Messages.DeleteReconfirm;
}
@section Scripts {
    <script>
        $(function () {

            var dt = new Macss.DataTables.MacssDataTable("#SampleList");
            dt.configure();

            //MacssDataTable（dataTables.fixedColumns.js）に表示する列が15件以上あると計算間違いで最左端列にスクロールバーが表示されるため、非表示にする
            $('.DTFC_LeftBodyLiner').css('overflow-y', 'hidden');

        });</script>
}
@using (Html.BeginForm("Delete", "Shipping", null, FormMethod.Post))
{
    <div class="alert alert-info">
        <span>以下を更新します。よろしいですか？</span>
    </div>
    <div class="row justify-content-between macss-form-button-group-row">
        <div class="col-4">
            <a class="btn btn-secondary" href="@Url.Action("Create")" role="button">@MacssWeb.Resources.ControlText.Back</a>
        </div>
    </div>
    <div class="accordion" id="ConditionAccordion">
        <div class="card">
            <div class="card-header macss-search-config-collapse-header" id="headingOne">
                <div class="mb-0">
                    <button class="btn macss-btn-condition-collapse" type="button" data-toggle="collapse" data-target="#ConditionMain" aria-expanded="true" aria-controls="ConditionMain">
                        <div class="d-inline-block" style="color:#333"></div>
                        <i id="CollapseHidden" class="fas fa-chevron-circle-up" aria-hidden="true" style="color: rgb(120, 188, 255);"></i>
                        <i id="CollapseShow" class="fas fa-chevron-circle-down" aria-hidden="true" style="color: rgb(120, 188, 255); display: none;"></i>
                    </button>
                </div>
            </div>
            <div id="ConditionMain" class="container-fluid mt-3 mb-3 pr-1 collapse show" aria-labelledby="headingOne" data-parent="#ConditionAccordion">
                <table class="table macss-form-table2">
                    <colgroup>
                        <col class="macss-form-table-title2">
                        <col class="macss-form-table-contents2">
                    </colgroup>
                    <tbody>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">仕入先</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">運送区分コード1</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">運送区分コード2</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">運賃明細コード</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">連携元区分</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">仕入先別運賃明細区分</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">基準運賃区分</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">明細適用区分</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">消費税区分</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">明細項番</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">帳票印字順番</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">FB運賃明細コード</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">使用不可開始日</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">
                                <label class="control-label" for="account_id">使用不可理由</label>
                            </th>
                            <td>
                                <div></div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}
<div class="mt-4"></div>
<div class="row justify-content-between macss-form-button-group-row">
    <div class="col-4">
        <a class="btn btn-secondary" href="@Url.Action("Create")" role="button">@MacssWeb.Resources.ControlText.Back</a>
    </div>
    <div class="col-4 text-right">
        <a role="button" class="btn btn-primary" data-toggle="modal" data-target="#ConfirmDialog">更新</a>
    </div>
</div>
<div class="modal" id="ConfirmDialog" tabindex="-1" role="dialog" aria-labelledby="ConfirmDialogTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ConfirmDialogTitle">@MacssWeb.Resources.Title.ExecConfirm</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                更新処理を実行します。よろしいですか？
            </div>
            <div class="modal-footer">
                <a class="btn btn-primary macss-btn" href="@Url.Action("Index")" role="button">@MacssWeb.Resources.ControlText.Yes</a>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">@MacssWeb.Resources.ControlText.No</button>
            </div>
        </div>
    </div>
</div>